contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - etcd
    - ca-certificates-bundle

entrypoint:
  command: /usr/bin/etcd

archs:
  - x86_64
  - aarch64
