contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
    - '@local /github/workspace/packages'
  packages:
    - alpine-release
    - sdk@local
entrypoint:
  command: /usr/bin/sdk

archs:
  - x86_64
  - arm64
