name: PreSubmit-Build

on:
  pull_request:

jobs:
  build:
    name: Build NGINX OCI image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nginx-version: [1.20.2, 1.23.1]
        include:
          - nginx-version: 1.20.2
            sha256: 958876757782190a1653e14dc26dfc7ba263de310e04c113e11e97d1bef45a42
          - nginx-version: 1.23.1
            sha256: 5eee1bd1c23e3b9477a45532f1f36ae6178b43d571a9607e6953cef26d5df1e2

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0

    - name: Generate snapshot date
      id: snapshot-date
      run: |
        echo ::set-output name=date::$(date -u +%Y%m%d)
      shell: bash


    - uses: sigstore/cosign-installer@main
    - uses: chainguard-dev/actions/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        empty-workspace: true
        archs: x86_64,aarch64,armv7
        template: "{\"Version\": \"${{ matrix.nginx-version }}\", \"SHA\": \"${{ matrix.sha256 }}\"}"

    - uses: distroless/actions/apko-build@main
      with:
        config: apko.yaml
        tag: nginx:${{ steps.snapshot-date.outputs.date }}
        keyring-append: /github/workspace/melange.rsa.pub
        archs: x86_64,aarch64,armv7
        source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
        additional-tags: ${{ matrix.nginx-version }}

    - name: Smoke Test
      run: |
        IMAGE_NAME=$(docker load < output.tar | grep "Loaded image" | sed 's/^Loaded image: //')
        IMAGE_NAME=$IMAGE_NAME ./test.sh

    - uses: actions/upload-artifact@v3
      with:
        name: nginx.tar
        path: ./output.tar
