package:
  name: melange
  version: 0.0.1
  epoch: 0
  description: "Melange"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: Apache-2.0
  dependencies:
    runtime:

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - go
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/melange
  - runs: |
      make melange
  - uses: autoconf/make-install
