contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - '@local /github/workspace/packages'
  packages:
    - ca-certificates-bundle
    - alpine-base
    - bubblewrap
    - melange@local

paths:
  - path: /work
    type: directory
    permissions: 0o777

work-dir: /work

entrypoint:
  command: /usr/bin/melange
cmd: --help

archs:
  - x86_64
  - aarch64
  - armv7

os-release:
  name: Alpine Linux
  id: alpine
  version-id: 3.17
  pretty-name: Alpine Linux 3.17
  home-url: https://alpinelinux.org/
  bug-report-url: https://gitlab.alpinelinux.org/alpine/aports/-/issues
