contents:
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - wolfictl
    - coreutils
    - bash
    - busybox
    - gitsign
    - make
    - graphviz
    - git

entrypoint:
  command: /usr/bin/wolfictl

command: -h
