contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - alpine-baselayout
    - php81
    - php81-common
    - php81-curl
    - php81-openssl
    - php81-xml
    - php81-pdo
    - php81-sqlite3
    - php81-phar

entrypoint:
  command: /usr/bin/php81

paths:
  - path: /app
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

work-dir: /app

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin

accounts:
  groups:
    - groupname: php
      gid: 65532
  users:
    - username: php
      uid: 65532
      gid: 65532
  run-as: 65532
