contents:
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - sdk
    - grype
    - apk-tools
    - gcsfuse
    - git
    - gitsign

environment:
  COLORTERM: truecolor
  TERM: xterm-256color

entrypoint:
  command: /usr/bin/sdk
