contents:
  packages:
    - alpine-baselayout-data
    - alpine-release==3 # TODO: unlock this, some issue using terraform
    - ca-certificates-bundle
    - musl==1 # TODO: unlock this, some issue using terraform
