name: image-summary
inputs:
  gcsBucketName:
    default: ''
runs:
  using: composite
  steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

    # GCloud-based, setup OIDC->SA auth
    - id: gcrauth1
      if: contains(inputs.apkoBaseTag, 'gcr.io/') || contains(inputs.apkoBaseTag, 'pkg.dev/')
      uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # v1.0.0
      with:
        workload_identity_provider: ${{ inputs.gcrAuthWorkloadIdentityProvider }}
        service_account: ${{ inputs.gcrAuthServiceAccount }}
    - id: gcrauth2
      if: contains(inputs.apkoBaseTag, 'gcr.io/') || contains(inputs.apkoBaseTag, 'pkg.dev/')
      uses: google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce # v1.0.1
      with:
        project_id: ${{ inputs.gcrAuthProjectId }}
        install_components: beta
    - id: gcrauth3
      if: contains(inputs.apkoBaseTag, 'gcr.io/') || contains(inputs.apkoBaseTag, 'pkg.dev/')
      shell: bash
      run: |
        gcloud auth configure-docker "$(echo ${{ inputs.apkoBaseTag }} | cut -d / -f 1)"

    - name: Setup cosign
      uses: sigstore/cosign-installer@main

    - id: create-image-summary
      shell: bash
      run: |
        echo '${{ inputs.imageSummaryJson }}' > summary.json

        # Use the SBOM to get the package version, add to dynamic.resolved list
        ref="$(cat summary.json | jq -r .ref)"
        i=0
        for line in $(cat summary.json | jq -c .tags[]); do
          pkg="$(echo "${line}" | jq -r .dynamic.package)"
          if [[ "${pkg}" != "" ]]; then
            primary="$(echo "${line}" | jq -r .primary)"
            version="$(cosign download sbom --platform=linux/amd64 "${ref}:${primary}" 2>/dev/null | jq -r '.packages[] | select(.name == "'${pkg}'") | .versionInfo')"
            if [[ "${version}" != "" ]]; then
              all_dynamic_versions=""
              prefix="$(echo "${line}" | jq -r .dynamic.prefix)"
              version_no_epoch="$(echo "${version}" | cut -d- -f1)"
              tmp=""
              for v in ${version_no_epoch//./ }; do
                if [[ "${tmp}" == "" ]]; then
                  tmp="${v}"
                else
                  tmp="${tmp}.${v}"
                fi
                if [[ "${all_dynamic_versions}" == "" ]]; then
                  all_dynamic_versions="${prefix}${tmp}"
                else
                  all_dynamic_versions="${all_dynamic_versions},${prefix}${tmp}"
                fi
              done
              all_dynamic_versions="${all_dynamic_versions},${prefix}${version}"
              resolved="$(printf "${all_dynamic_versions}" | jq -R -c '.|split(",")')"
              cat summary.json | jq '.tags['${i}'].dynamic.resolved = '${resolved}'' > summary.json.tmp
              mv summary.json.tmp summary.json
            fi
          fi
          i=$((i+1))
        done

        # Minify
        cat summary.json | jq -c -M > summary.json.tmp
        mv summary.json.tmp summary.json

        echo "Image summary for ${{ inputs.imageName }}:"
        cat summary.json | jq

        # Create the SVG
        i=0
        for line in $(cat summary.json | jq -c .tags[]); do
          message="$(echo "${line}" | jq -r .primary)"
          static="$(echo "${line}" | jq -r .static[] | xargs | sed 's/ /, /g')"
          dynamic="$(echo "${line}" | jq -r .dynamic.resolved[] | xargs | sed 's/ /, /g')"
          if [[ "${static}" != "" && "${dynamic}" != "" ]]; then
            message="${message} (${static}, ${dynamic})"
          elif [[ "${static}" != "" ]]; then
            message="${message} (${static})"
          elif [[ "${dynamic}" != "" ]]; then
            message="${message} (${dynamic})"
          fi
          message="$(echo "${message}" | sed 's/ /%20/g' | sed 's/,/%2C/g' | sed 's/(/%28/g' | sed 's/)/%29/g')"
          curl -s -L -o "image-part-${i}.svg" \
            "https://img.shields.io/static/v1?label=&color=white&style=flat-square&message=${message}"
          i=$((i+1))
        done

        # Combine using svg_stack python module
        pip install lxml==4.9.2 svg-stack==0.1.0
        python -c '
        import glob, svg_stack as ss
        doc = ss.Document()
        layout = ss.VBoxLayout()
        for filename in glob.glob("image-part-*.svg"):
            layout.addSVG(filename, alignment=ss.AlignLeft)
        doc.setLayout(layout)
        doc.save("image.svg")'
        rm -rf image-part-*.svg

        rm -rf image-summary-output/
        mkdir image-summary-output/
        mv summary.json "image-summary-output/${{ inputs.imageName }}.json"
        mv image.svg "image-summary-output/${{ inputs.imageName }}.svg"

    # Auth to gcloud
    - id: gcsauth1
      if: inputs.gcsBucketName != ''
      uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # v1.0.0
      with:
        workload_identity_provider: ${{ inputs.gcsAuthWorkloadIdentityProvider }}
        service_account: ${{ inputs.gcsAuthServiceAccount }}
    - id: gcsauth2
      if: inputs.gcsBucketName != ''
      uses: google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce # v1.0.1
      with:
        project_id: ${{ inputs.gcsAuthProjectId }}
        install_components: beta

    # Upload to GCS
    - id: gcsupload1
      if: inputs.gcsBucketName != ''
      shell: bash
      run: |
        gsutil rsync image-summary-output/ gs://${{ inputs.gcsBucketName }}/summary

    - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
      if: always()
      with:
        name: image-summary
        path: image-summary-output

    # Slack notification if build failing
    - uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
      #if: failure() && inputs.slackWebhookUrl != ''
      if: failure() && inputs.slackWebhookUrl == 'TODO disabled'
      id: slack
      with:
        payload: '{"text": "[image-summary] ${{ inputs.imageName }} failed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slackWebhookUrl }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Touch actions file to prevent postrun failure
      if: always()
      shell: bash
      run: |
        set -x && [[ -f .github/actions/image-summary/action.yml ]] || ( \
          mkdir -p .github/actions/image-summary/ && echo 'runs: {using: composite, steps: []}' > .github/actions/image-summary/action.yml )
