on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

  # Allow manually triggered workflows by maintainers without any
  # parameters to trigger a proactive rebuild (e.g. when a new
  # apko lands)
  workflow_dispatch: {}

name: Create Release

# Don't run multiple releases concurrently.
concurrency: release

jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest

    outputs:
      image-refs: ${{ steps.emit-refs.outputs.image-refs }}

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: sigstore/cosign-installer@main

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0

    - uses: chainguard-dev/actions/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        archs: x86_64,aarch64,armv7

    - uses: distroless/actions/apko-snapshot@main
      with:
        config: apko.yaml
        base-tag: ghcr.io/${{ github.repository }}
        keyring-append: /github/workspace/melange.rsa.pub
        archs: x86_64,aarch64,armv7

    - name: Emit Image Refs output
      id: emit-refs
      run: |
        cat apko.images | sed 's/$/\n/g' | grep -v '^$' | jq -R -s -c 'split("\n")[:-1]' | jq .
        echo ::set-output name=image-refs::$(cat apko.images | sed 's/$/\n/g' | grep -v '^$' | jq -R -s -c 'split("\n")[:-1]')

    - if: ${{ failure() }}
      name: Setup upterm session
      uses: lhotari/action-upterm@v1

  scan:
    name: Scan apko images
    needs: build
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    strategy:
      matrix:
        ref: ${{ fromJson(needs.build.outputs.image-refs) }}
    steps:
      - run: |
          echo ${{ matrix.ref }}

      - uses: distroless/actions/vul-scans@main
        id: scans
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          image: ${{ matrix.ref }}
          RUN_SNYK: "false"
          RUN_GRYPE: "false"
          DOCKER_LOGIN: 'true'

      - name: Image Vulnerability scan output
        shell: bash
        env:
          SNYK_COUNT: ${{ steps.scans.outputs.SNYK_COUNT }}
          GRYPE_COUNT: ${{ steps.scans.outputs.GRYPE_COUNT }}
          TRIVY_COUNT: ${{ steps.scans.outputs.TRIVY_COUNT }}
        run: |
          echo "Image Vulnerability scan output" >> $GITHUB_STEP_SUMMARY
          echo "Image ID: ${{ matrix.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Snyk Count: $SNYK_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "Grype Count: $GRYPE_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "Trivy Count: $TRIVY_COUNT" >> $GITHUB_STEP_SUMMARY

  generate-readme:
    name: Generate README
    needs: scan
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Enable OIDC
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Generate README
        uses: distroless/readme-generator@push-commit
        with:
          repo: https://github.com/distroless/hello-world
          name: hello-world
          location: cgr.dev/chainguard/hello-world
          description: "Hello, world!"
          output-path: README-GENERATED.md
          push-to-repo: true
