contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
  packages:
    - alpine-baselayout-data
    - alpine-release
    - apk-tools
    - busybox
    - libc-utils

os-release:
  name: Alpine Linux
  id: alpine
  version-id: 3.17
  pretty-name: Alpine Linux 3.17
  home-url: https://alpinelinux.org/
  bug-report-url: https://gitlab.alpinelinux.org/alpine/aports/-/issues
