contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - rabbitmq-server
    - wolfi-baselayout
    - bash

paths:
  - path: /app
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
  - path: /var/lib/rabbitmq/mnesia
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
  - path: /var/log/rabbitmq
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
  - path: /home/rabbitmq
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
  - path: /var/log/rabbitmq/rabbit
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999

work-dir: /var/lib/rabbitmq

entrypoint:
  command: /usr/sbin/rabbitmq-server

environment:
  RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
  RABBITMQ_ADVANCED_CONFIG_FILE: /etc/rabbitmq/advanced.config
  RABBITMQ_CONF_ENV_FILE: /etc/rabbitmq/rabbitmq-env.conf
  HOME: /var/lib/rabbitmq

# By convention, the official Docker node image defines a `node` user, but
# doesn't run as it unless the image based on it specifies that user.
accounts:
  groups:
    - groupname: rabbitmq
      gid: 999
  users:
    - username: rabbitmq
      uid: 999
  run-as: 999

archs:
- x86_64
- aarch64
