contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - alpine-baselayout-data
    - ca-certificates-bundle
    - git
    - git-lfs
    - openssh-client

entrypoint:
  command: /usr/bin/git

work-dir: /home/git

accounts:
  groups:
    - groupname: git
      gid: 65532
  users:
    - username: git
      uid: 65532
      gid: 65532

os-release:
  name: Alpine Linux
  id: alpine
  version-id: 3.17
  pretty-name: Alpine Linux 3.17
  home-url: https://alpinelinux.org/
  bug-report-url: https://gitlab.alpinelinux.org/alpine/aports/-/issues
