on:
  pull_request:
jobs:
  presubmit-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - uses: ./.github/actions/verify-readme
      with:
        gcsBucketName: ${{ secrets.GCS_BUCKET_NAME }}
