contents:
  packages:
    - alpine-keys
    - ca-certificates-bundle
    - wolfi-base
    - bubblewrap
    - melange-head

paths:
  - path: /work
    type: directory
    permissions: 0o777

work-dir: /work

entrypoint:
  command: /usr/bin/melange
cmd: --help
