contents:
  packages:
    - ca-certificates-bundle
    - alpine-baselayout-data
    - alpine-release==3
    - gcc
    - musl-dev==1
    - busybox

paths:
  - path: /work
    type: directory
    permissions: 0o777

work-dir: /work

entrypoint:
  command: /usr/bin/gcc
cmd: --help
