contents:
  repositories:
    - https://packages.wolfi.dev/os
    - '@local /github/workspace/packages'
  packages:
    - ca-certificates-bundle
    - wolfi-base
    - apko@local

paths:
  - path: /work
    type: directory
    permissions: 0o777

work-dir: /work

entrypoint:
  command: /usr/bin/apko
cmd: --help

archs:
  - x86_64
  - aarch64
