contents:
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - busybox
    - build-base
    - go
    - ko

archs:
- amd64
- arm64

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/ko
